@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "model.order.Order#setState(OrderState)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "model.order.Order",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_106006350 { 
   	label=order
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_2113869129 { 
   	label=Order
	labeljust=l
	fillcolor=white
	style=filled
   
   Order574903223XXXnextState0[
	label="+ nextState()"
	style=filled
	fillcolor=white
	tooltip="Order

null"
	fontcolor=darkgreen
];

Order574903223XXXsetState1556182525[
	label="+ setState()"
	style=filled
	fillcolor=white
	tooltip="Order

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_109757585 { 
   	label=state
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1171067552 { 
   	label=OutForDeliveryState
	labeljust=l
	fillcolor=white
	style=filled
   
   OutForDeliveryState571151988XXXnext76453678[
	label="+ next()"
	style=filled
	fillcolor=white
	tooltip="OutForDeliveryState

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1790510388 { 
   	label=ConfirmedState
	labeljust=l
	fillcolor=white
	style=filled
   
   ConfirmedState571151988XXXnext76453678[
	label="+ next()"
	style=filled
	fillcolor=white
	tooltip="ConfirmedState

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_556433618 { 
   	label=PlacedState
	labeljust=l
	fillcolor=white
	style=filled
   
   PlacedState571151988XXXnext76453678[
	label="+ next()"
	style=filled
	fillcolor=white
	tooltip="PlacedState

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_644095057 { 
   	label=PreparingState
	labeljust=l
	fillcolor=white
	style=filled
   
   PreparingState571151988XXXnext76453678[
	label="+ next()"
	style=filled
	fillcolor=white
	tooltip="PreparingState

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_637428636 { 
   	label=controller
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1392559366 { 
   	label=RestaurantDashboardController
	labeljust=l
	fillcolor=white
	style=filled
   
   RestaurantDashboardController2073764737XXXinitialize0[
	label="+ initialize()"
	style=filled
	fillcolor=white
	tooltip="RestaurantDashboardController

null"
	fontcolor=darkgreen
];

RestaurantDashboardController2073764737XXXrefreshOrders0[
	label="+ refreshOrders()"
	style=filled
	fillcolor=white
	tooltip="RestaurantDashboardController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1591661018 { 
   	label=MyOrdersController
	labeljust=l
	fillcolor=white
	style=filled
   
   MyOrdersController2073764737XXXinitialize0[
	label="+ initialize()"
	style=filled
	fillcolor=white
	tooltip="MyOrdersController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_184304283 { 
   	label=RestaurantOwnerController
	labeljust=l
	fillcolor=white
	style=filled
   
   RestaurantOwnerController2073764737XXXacceptOrder76453678[
	label="+ acceptOrder()"
	style=filled
	fillcolor=white
	tooltip="RestaurantOwnerController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_331593123 { 
   	label=DeliveryController
	labeljust=l
	fillcolor=white
	style=filled
   
   DeliveryController2073764737XXXinitialize0[
	label="+ initialize()"
	style=filled
	fillcolor=white
	tooltip="DeliveryController

null"
	fontcolor=darkgreen
];

DeliveryController2073764737XXXrefreshOrders0[
	label="+ refreshOrders()"
	style=filled
	fillcolor=white
	tooltip="DeliveryController

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_950394699 { 
   	label=command
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1733104700 { 
   	label=PlaceOrderCommand
	labeljust=l
	fillcolor=white
	style=filled
   
   PlaceOrderCommand568675962XXXexecute0[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="PlaceOrderCommand

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_99218 { 
   	label=dao
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1234979936 { 
   	label=OrderDAO
	labeljust=l
	fillcolor=white
	style=filled
   
   OrderDAO99218XXXgetOrdersByCustomer104431[
	label="+ getOrdersByCustomer()"
	style=filled
	fillcolor=white
	tooltip="OrderDAO

null"
	fontcolor=darkgreen
];

OrderDAO99218XXXgetOrdersByDeliveryStaff104431[
	label="+ getOrdersByDeliveryStaff()"
	style=filled
	fillcolor=white
	tooltip="OrderDAO

null"
	fontcolor=darkgreen
];

OrderDAO99218XXXgetOrdersByRestaurant104431[
	label="+ getOrdersByRestaurant()"
	style=filled
	fillcolor=white
	tooltip="OrderDAO

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
ConfirmedState571151988XXXnext76453678 -> Order574903223XXXsetState1556182525;
DeliveryController2073764737XXXinitialize0 -> OrderDAO99218XXXgetOrdersByDeliveryStaff104431;
DeliveryController2073764737XXXrefreshOrders0 -> OrderDAO99218XXXgetOrdersByDeliveryStaff104431;
MyOrdersController2073764737XXXinitialize0 -> OrderDAO99218XXXgetOrdersByCustomer104431;
Order574903223XXXnextState0 -> OutForDeliveryState571151988XXXnext76453678;
OrderDAO99218XXXgetOrdersByCustomer104431 -> Order574903223XXXsetState1556182525;
OrderDAO99218XXXgetOrdersByDeliveryStaff104431 -> Order574903223XXXsetState1556182525;
OrderDAO99218XXXgetOrdersByRestaurant104431 -> Order574903223XXXsetState1556182525;
OutForDeliveryState571151988XXXnext76453678 -> Order574903223XXXsetState1556182525;
PlaceOrderCommand568675962XXXexecute0 -> Order574903223XXXnextState0;
PlacedState571151988XXXnext76453678 -> Order574903223XXXsetState1556182525;
PreparingState571151988XXXnext76453678 -> Order574903223XXXsetState1556182525;
RestaurantDashboardController2073764737XXXinitialize0 -> OrderDAO99218XXXgetOrdersByRestaurant104431;
RestaurantDashboardController2073764737XXXrefreshOrders0 -> OrderDAO99218XXXgetOrdersByRestaurant104431;
RestaurantOwnerController2073764737XXXacceptOrder76453678 -> Order574903223XXXnextState0;
    
}
@enduml